<?php
/* 
(C) 2006- Sigbert Klinke (sigbert@wiwi.hu-berlin.de)

This file is part of R/Octave Extension for Mediawiki.

The R/Octave Extension is free software: you can 
redistribute it and/or modify it under the terms of 
the GNU General Public License as published by the
Free Software Foundation, either version 3 of the 
License, or (at your option) any later version.

The R/Octave Extension is distributed in the hope that 
It will be useful, but WITHOUT ANY WARRANTY; without 
even the implied warranty of MERCHANTABILITY or 
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
Public License for more details.

You should have received a copy of the GNU General 
Public License along with the R/Octave Extension. 
If not, see http://www.gnu.org/licenses/.
*/

// from http://www.mathworks.de/de/help/matlab/functionlist.html
$commands = array(
		  // Category: Entering Commands
		  'clc' =>                 array(R_CMD_UI, '/\bclc\b/'), 
		  'diary' =>               array(R_CMD_IO, '/\bdiary\b/'),
		  'home' =>                array(R_CMD_UI, '/\bhome\b/'),
		  'more' =>                array(R_CMD_UI, '/\bmore\b/'),
		  // commandhistory commandwindow
		  'command' =>             array(R_CMD_UI, '/\bcommand(history|window)\b/'),
		  // Category: Special Characters
		  '!' =>                   array(R_CMD_EXEC, '!'),
		  // Category: Data Types
		  'table' =>               array(R_CMD_IO, '/\b(write|read)table\b/'),
		  'feval' =>               array(R_CMD_EXEC, '/\bfeval\b/'),
		  'str2func' =>	           array(R_CMD_EXEC, '/\bstr2func\b/'),
		  // localfunctions functions
		  'functions' =>           array(R_CMD_INFO, '/\b(local)?functions\b/'),
		  // Category: Formatting and Annotation
		  'pan' =>                 array(R_CMD_UI, '/\bpan\b/'),
		  'rotate3d' =>            array(R_CMD_UI, '/\brotate3d\b/'),
		  'selectmoveresize' =>    array(R_CMD_UI, '/\bselectmoveresize\b/'),
		  'datacursormode' =>      array(R_CMD_UI, '/\bdatacursormode\b/'),
		  'figurepalette' =>       array(R_CMD_UI, '/\bfigurepalette\b/'),
		  'plotbrowser' =>         array(R_CMD_UI, '/\bplotbrowser\b/'),
		  'plotedit' =>            array(R_CMD_UI, '/\bplotedit\b/'),
		  'plottools' =>           array(R_CMD_UI, '/\bplottools\b/'),
		  'propertyeditor' =>      array(R_CMD_UI, '/\bpropertyeditor\b/'),
		  'showplottool' =>        array(R_CMD_UI, '/\bshowplottool\b/'),
		  'brush' =>               array(R_CMD_UI, '/\bbrush\b/'),
		  // 'datacursormode' =>      array(R_CMD_UI, '/\bdatacursormode\b/'),
		  'linkdata' =>            array(R_CMD_UI, '/\blinkdata\b/'),
		  'refreshdata' =>         array(R_CMD_UI, '/\brefreshdata\b/'),
		  // Category: Image
		  'imread' =>              array(R_CMD_IO, '/\bimread\b/'), 
		  'imwrite' =>             array(R_CMD_IO, '/\bimwrite\b/'),
		  'imfinfo' =>             array(R_CMD_INFO, '/\bimfinfo\b/'),
		  'imformats' =>           array(R_CMD_IO, '/\bimformats\b/'),
		  // Category Printing and Exporting
		  'printopt' =>            array(R_CMD_IO, '/\bprintopt\b/'),
		  'printdlg' =>            array(R_CMD_UI, '/\bprintdlg\b/'),
		  'savefig' =>             array(R_CMD_IO, '/\bsavefig\b/'), 
		  'openfig' =>             array(R_CMD_IO, '/\bopenfig\b/'),
		  'hgexport' =>            array(R_CMD_IO, '/\bhgexport\b/'),
		  'hgsave' =>              array(R_CMD_IO, '/\bhgsave\b/'),
		  'hgload' =>              array(R_CMD_IO, '/\bhgload\b/'),
		  'saveas' =>              array(R_CMD_IO, '/\bsaveas\b/'),
		  // Category: Graphics Objects
		  'delete' =>              array(R_CMD_IO, '/\bdelete(Col|HDU|Key|Record|Rows|property)?\b/'),
		  'propedit' =>            array(R_CMD_UI, '/\bpropedit\b/'),
		  // Category: Scripts
		  'edit' =>                array(R_CMD_IO, '/\bedit\b/'),
		  'input' =>               array(R_CMD_IO, '/\binput\b/'),
		  'publish' =>             array(R_CMD_IO, '/\bpublish\b/'),
		  'notebook' =>            array(R_CMD_UI, '/\bnotebook\b/'),
		  'grabcode' =>            array(R_CMD_IO, '/\bgrabcode\b/'),
		  'snapnow' =>             array(R_CMD_IO, '/\bsnapnow\b/'),
		  // Category: Functions
		  'onCleanup' =>           array(R_CMD_IO, '/\bonCleanup'),
		  // Category: Debugging
		  'db' =>                  array(R_CMD_UI, '/\bdb(clear|cont|down|quit|stack|status|step|stop|type|up)\b/'),
		  'checkcode' =>           array(R_CMD_IO|R_CMD_EXEC, '/\bcheckcode\b/'),
		  'keyboard' =>            array(R_CMD_IO, '/\bkeyboard\b/'),
		  'mlintrpt' =>            array(R_CMD_IO|R_CMD_EXEC, '/\bmlintrpt\b/'),
		  // Category: Programming Utilities 
		  // eval evalc evalin
		  'eval' =>	           array(R_CMD_EXEC, '/\beval(c|in)?\b/'),
		  'run' =>                 array(R_CMD_EXEC, '/\brun\b/'),
		  'builtin' =>             array(R_CMD_EXEC, '/\bbuiltin\b/'),
		  //depdir depfun    
		  'dep' =>                 array(R_CMD_IO, '/\bdep(dir|fun)\b/'),
		  'mfilename' =>           array(R_CMD_INFO, '/\bmfilename\b/'),
		  'pcode' =>               array(R_CMD_IO, '/\bpcode\b/'),
		  // taken out 02 Nov 13 'timer' =>               array(, '/\btimer\b/'),
		  // Category: Workspace Variables
		  'openvar' =>             array(R_CMD_UI, '/\bopenvar\b/'),
		  'load' =>                array(R_CMD_IO, '/\bload\b/'),
		  'save' =>                array(R_CMD_IO, '/\bsave\b/'), 
		  'matfile' =>             array(R_CMD_IO, '/\bmatfile\b/'),
		  'workspace' =>           array(R_CMD_UI, '/\bworkspace\b/'),
		  // Category: Data Import and Export
		  'importdata' =>          array(R_CMD_IO, '/\bimportdata\b/'),
		  'uiimport' =>            array(R_CMD_IO|R_CMD_UI, '/\buiimport\b/'),
		  // csvread csvwrite
		  'csv' =>                 array(R_CMD_IO, '/\bcsv(read|write)\b/'),
		  // dlmread dlmwrite
		  'dlm' =>                 array(R_CMD_IO, '/\bdlm(read|write)\b/'),
		  'fileread' =>            array(R_CMD_IO, '/\bfileread\b/'),
		  'textread' =>            array(R_CMD_IO, '/\btextread\b/'),
		  'textscan' =>            array(R_CMD_IO, '/\btextscan\b/'),
		  'readtable' =>           array(R_CMD_IO, '/\breadtable\b/'),
		  'writetable' =>          array(R_CMD_IO, '/\bwritetable\b/'),
		  'type' =>                array(R_CMD_INFO, '/\btype\b/'),
		  // xlsinfo xlsread xlswrite
		  'xls' =>                 array(R_CMD_IO, '/\bxls(info|read|write)\b/'),
		  'fclose' =>              array(R_CMD_IO, '/\bfclose\b/'),
		  'feof' =>                array(R_CMD_IO, '/\bfeof\b/'),
		  'fgetl' =>               array(R_CMD_IO, '/\bfgetl\b/'),
		  'fgets' =>               array(R_CMD_IO, '/\bfgets\b/'),
		  'fopen' =>               array(R_CMD_IO, '/\bfopen\b/'),
		  'fprintf' =>             array(R_CMD_IO, '/\bfprintf\b/'),
		  'fread' =>               array(R_CMD_IO, '/\bfread\b/'),
		  'frewind' =>             array(R_CMD_IO, '/\bfrewind\b/'),
		  'fscanf' =>              array(R_CMD_IO, '/\bfscanf\b/'),
		  'fseek' =>               array(R_CMD_IO, '/\bfseek\b/'),
		  'ftell' =>               array(R_CMD_IO, '/\bftell\b/'),
		  'fwrite' =>              array(R_CMD_IO, '/\bfwrite\b/'),
		  'exifread' =>            array(R_CMD_IO, '/\bexifread\b/'),
		  'Tiff' =>                array(R_CMD_IO, '/\bTiff\b/'),
		  'nccreate' =>            array(R_CMD_IO, '/\bnccreate\b/'),
		  'ncdisp' =>              array(R_CMD_IO, '/\bncdisp\b/'),
		  'ncinfo' =>              array(R_CMD_IO, '/\bncinfo\b/'),
		  // ncread ncreadatt
		  'ncread' =>              array(R_CMD_IO, '/\bncread(att)?\b/'),
		  // ncwrite ncwriteatt ncwriteschema
		  'ncwrite' =>             array(R_CMD_IO, '/\bncwrite(att|schema)?\b/'),
		  'netcdf' =>              array(R_CMD_IO, '/\bnetcdf\b/'),
		  'h5create' =>            array(R_CMD_IO, '/\bh5create\b/'),   
		  'h5disp' =>              array(R_CMD_IO, '/\bh5disp\b/'), 
		  'h5info' =>              array(R_CMD_IO, '/\bh5info\b/'), 
		  // h5read h5readatt
		  'h5read' =>              array(R_CMD_IO, '/\bh5read(att)?\b/'), 
		  // h5write h5writeatt h5writeschema
		  'h5write' =>             array(R_CMD_IO, '/\bh5write(att|schema)?\b/'),
		  // H5.*
		  'H5.' =>                 array(R_CMD_IO, '/\bH5\.[\w]+\b/'), 
		  'H5A.' =>                array(R_CMD_IO, '/\bH5A\.[\w]+\b/'), 
		  'H5D.' =>                array(R_CMD_IO, '/\bH5D\.[\w]+\b/'), 
		  'H5DS.' =>               array(R_CMD_IO, '/\bH5DS\.[\w]+\b/'), 
		  'H5E.' =>                array(R_CMD_IO, '/\bH5E\.[\w]+\b/'),  
		  'H5F.' =>                array(R_CMD_IO, '/\bH5F\.[\w]+\b/'), 
		  'H5G.' =>                array(R_CMD_IO, '/\bH5G\.[\w]+\b/'), 
		  'H5I.' =>                array(R_CMD_IO, '/\bH5I\.[\w]+\b/'), 
		  'H5L.' =>                array(R_CMD_IO, '/\bH5L\.[\w]+\b/'), 
		  'H5ML.' =>               array(R_CMD_IO, '/\bH5ML\.[\w]+\b/'), 
		  'H5O.' =>                array(R_CMD_IO, '/\bH5O\.[\w]+\b/'), 
		  'H5P.' =>                array(R_CMD_IO, '/\bH5P\.[\w]+\b/'),  
		  'H5R.' =>                array(R_CMD_IO, '/\bH5R\.[\w]+\b/'),  
		  'H5S.' =>                array(R_CMD_IO, '/\bH5S\.[\w]+\b/'), 
		  'H5T.' =>                array(R_CMD_IO, '/\bH5T\.[\w]+\b/'), 
		  // hdf hdfinfo hdfread
		  'hdf' =>                 array(R_CMD_IO, '/\bhdf(info|read)?\b/'), 
		  'fits' =>                array(R_CMD_IO, '/\bfits(disp|info|read|write)\b/'),
		  'File' =>                array(R_CMD_IO, '/\b(create|open|close|delete)File\b/'),
		  'fileName' =>            array(R_CMD_IO, '/\bfileName\b/'),
		  'fileMode' =>            array(R_CMD_IO, '/\bfileMode\b/'),
		  'createImg' =>           array(R_CMD_IO, '/\bcreateImg\b/'), 	
		  'getImgSize' =>          array(R_CMD_IO, '/\bgetImgSize'),
		  'getImgType' =>          array(R_CMD_IO, '/\bgetImgType\b/'),	
		  'readImg' =>             array(R_CMD_IO, '/\breadImg\b/'),	
		  'setBscale' =>           array(R_CMD_IO, '/\bsetBscale\b/'),	
		  'writeImg' =>            array(R_CMD_IO, '/\bwriteImg\b/'),	
		  'readCard' =>            array(R_CMD_IO, '/\breadCard\b/'),	
		  'readKey' =>             array(R_CMD_IO, '/\breadKey(Cmplx|Dbl|LongLong|LongStr|Unit|Record)?\b/'),
		  'writeComment' =>        array(R_CMD_IO, '/\bwriteComment\b/'),	
		  'writeDate' =>           array(R_CMD_IO, '/\bwriteDate\b/'),	
		  'writeKey' =>            array(R_CMD_IO, '/\bwriteKey\b/'),	
		  'writeKeyUnit' =>        array(R_CMD_IO, '/\bwriteKeyUnit\b/'),	
		  'writeHistory' =>        array(R_CMD_IO, '/\bwriteHistory\b/'),	
		  'getHdrSpace' =>         array(R_CMD_IO, '/\bgetHdrSpace\b/'),	
		  'copyHDU' =>             array(R_CMD_IO, '/\bcopyHDU\b/'),	
		  'getHDUnum' =>           array(R_CMD_IO, '/\bgetHDUnum\b/'),	
		  'getHDUtype' =>          array(R_CMD_IO, '/\bgetHDUtype\b/'),	
		  'getNumHDUs' =>          array(R_CMD_IO, '/\bgetNumHDUs\b/'),	
		  'movAbsHDU' =>           array(R_CMD_IO, '/\bmovAbsHDU\b/'),	
		  'movNamHDU' =>           array(R_CMD_IO, '/\bmovNamHDU\b/'),	
		  'movRelHDU' =>           array(R_CMD_IO, '/\bmovRelHDU\b/'),	
		  'writeChecksum' =>       array(R_CMD_IO, '/\bwriteChecksum\b/'),
		  'deleteHDU' =>           array(R_CMD_IO, '/\bdeleteHDU\b/'),		
		  'imgCompress' =>         array(R_CMD_IO, '/\bimgCompress\b/'),	
		  'isCompressedImg' =>     array(R_CMD_IO, '/\bisCompressedImg\b/'),
		  'setCompressionType' =>  array(R_CMD_IO, '/\bsetCompressionType\b/'),          
		  'setHCompScale' =>       array(R_CMD_IO, '/\bsetHCompScale\b/'),	
		  'setHCompSmooth' =>      array(R_CMD_IO, '/\bsetHCompSmooth\b/'),	
		  'setTileDim' =>          array(R_CMD_IO, '/\bsetTileDim\b/'),	
		  'createTbl' =>           array(R_CMD_IO, '/\bcreateTbl\b/'),	
		  'insert' =>              array(R_CMD_IO, '/\binsert(Img|Col|Rows|ATbl|BTbl)\b/'),	
		  'getAColParms' =>        array(R_CMD_IO, '/\bgetAColParms\b/'),	
		  'getBColParms' =>        array(R_CMD_IO, '/\bgetBColParms\b/'),	
		  'getColName' =>          array(R_CMD_IO, '/\bgetColName\b/'),	
		  'getColType' =>          array(R_CMD_IO, '/\bgetColType\b/'),	
		  'getEqColType' =>        array(R_CMD_IO, '/\bgetEqColType\b/'),	
		  'getNumCols' =>          array(R_CMD_IO, '/\bgetNumCols\b/'),	
		  'getNumRows' =>          array(R_CMD_IO, '/\bgetNumRows\b/'),	
		  'readATblHdr' =>         array(R_CMD_IO, '/\breadATblHdr\b/'),	
		  'readBTblHdr' =>         array(R_CMD_IO, '/\breadBTblHdr\b/'),	
		  'readCol' =>             array(R_CMD_IO, '/\breadCol\b/'),	
		  'setTscale' =>           array(R_CMD_IO, '/\bsetTscale\b/'),	
		  'writeCol' =>            array(R_CMD_IO, '/\bwriteCol\b/'),	
		  'getConstantValue' =>    array(R_CMD_IO, '/\bgetConstantValue\b/'),
		  'getVersion' =>          array(R_CMD_IO, '/\bgetVersion\b/'),	
		  'getOpenFiles' =>        array(R_CMD_IO, '/\bgetOpenFiles\b/'),	
		  'multiband' =>           array(R_CMD_IO, '/\bmultiband(read|write)\b/'),	
		  'cdfepoch' =>            array(R_CMD_IO, '/\bcdfepoch\b/'),	
		  'cdfinfo' =>             array(R_CMD_IO, '/\bcdfinfo\b/'),	
		  'cdfread' =>             array(R_CMD_IO, '/\bcdfread\b/'),	
		  'cdfwrite' =>            array(R_CMD_IO, '/\bcdfwrite\b/'),	
		  'todatenum' =>           array(R_CMD_IO, '/\btodatenum\b/'),	
		  'cdflib' =>              array(R_CMD_IO, '/\bcdflib\b/'),	
		  'audio' =>               array(R_CMD_IO, '/\baudio(info|read|write)\b/'),	
		  'mmfileinfo' =>          array(R_CMD_INFO, '/\bmmfileinfo\b/'),	
		  'movie2avi' =>           array(R_CMD_IO, '/\bmovie2avi\b/'),	
		  'Video' =>               array(R_CMD_IO, '/\bVideo(Reader|Writer)\b/'),	
		  'xml' =>                 array(R_CMD_IO, '/\bxml(read|write)\b/'),
		  'xslt' =>                array(R_CMD_IO, '/\bxslt\b/'),	  
		  'memmapfile' =>          array(R_CMD_IO, '/\bmemmapfile\b/'),
		  // Catgegory: File Operations
		  'dir' =>                 array(R_CMD_INFO, '/\bdir\b/'),
		  'ls' =>                  array(R_CMD_INFO, '/\bls\b/'),
		  'pwd' =>                 array(R_CMD_INFO, '/\bpwd\b/'),
		  'fileattrib' =>          array(R_CMD_IO, '/\bfileattrib\b/'),
		  'isdir' =>               array(R_CMD_INFO, '/\bisdir\b/'),
		  'visdiff' =>             array(R_CMD_INFO, '/\bvisdiff\b/'),
		  'what' =>                array(R_CMD_INFO, '/\bwhat\b/'),
		  'which' =>               array(R_CMD_IO, '/\bwhich\b/'),
		  'cd' =>                  array(R_CMD_IO, '/\bcd\b/'),
		  'copyfile' =>            array(R_CMD_IO, '/\bcopyfile\b/'),
		  'recycle' =>             array(R_CMD_IO, '/\brecycle\b/'),
		  'mkdir' =>               array(R_CMD_IO, '/\bmkdir\b/'),
		  'movefile' =>            array(R_CMD_IO, '/\bmovefile\b/'),
		  'rmdir' =>               array(R_CMD_IO,  '/\brmdir\b/'),
		  'open' =>                array(R_CMD_UI, '/\bopen\b/'),
		  'winopen' =>             array(R_CMD_UI, '/\bwinopen\b/'),
		  'filebrowser' =>         array(R_CMD_UI, '/\bfilebrowser\b/'),
		  'tempdir' =>             array(R_CMD_INFO, '/\btempdir\b/'),
		  'tempname' =>            array(R_CMD_INFO, '/\btempname\b/'),
		  'toolboxdir' =>          array(R_CMD_INFO, '/\btoolboxdir\b/'),
		  'gunzip' =>              array(R_CMD_IO, '/\bgunzip\b/'),
		  'gzip' =>                array(R_CMD_IO, '/\bgzip\b/'),
		  'tar' =>                 array(R_CMD_IO, '/\btar\b/'),
		  'untar' =>               array(R_CMD_IO, '/\buntar\b/'),
		  'unzip' =>               array(R_CMD_IO, '/\bunzip\b/'),
		  'zip' =>                 array(R_CMD_IO, '/\bzip\b/'),
		  'addpath' =>             array(R_CMD_IO, '/\baddpath\b/'),
		  'rmpath' =>              array(R_CMD_IO, '/\brmpath\b/'),
		  'path' =>                array(R_CMD_IO, '/\bpath\b/'),
		  'savepath' =>            array(R_CMD_IO, '/\bsavepath\b/'),
		  'userpath' =>            array(R_CMD_IO, '/\buserpath\b/'),
		  'genpath' =>             array(R_CMD_IO, '/\bgenpath\b/'),
		  'pathtool' =>            array(R_CMD_UI, '/\bpathtool\b/'),
		  'restoredefaultpath' =>  array(R_CMD_IO, '/\brestoredefaultpath\b/'),
		  // Category: Operating System Commands
		  'clipboard' =>           array(R_CMD_IO, '/\bclipboard\b/'),
		  'computer' =>            array(R_CMD_INFO, '/\bcomputer\b/'),
		  'dos' =>                 array(R_CMD_EXEC, '/\bdos\b/'),
		  'getenv' =>              array(R_CMD_INFO, '/\bgetenv\b/'),
		  'perl' =>                array(R_CMD_EXEC, '/\bperl\b/'),
		  'setenv' =>              array(R_CMD_IO, '/\bsetenv\b/'),
		  'system' =>              array(R_CMD_EXEC, '/\bsystem\b/'),
		  'unix' =>                array(R_CMD_EXEC, '/\bunix\b/'),
		  'winqueryreg' =>         array(R_CMD_INFO, '/\bwinqueryreg\b/'),
		  // Category: Internet File Access
		  'ftp' =>                 array(R_CMD_IO, '/\bftp\b/'),
		  'sendmail' =>            array(R_CMD_IO, '/\bsendmail\b/'),
		  'urlread' =>             array(R_CMD_IO, '/\burlread\b/'),
		  'urlwrite' =>            array(R_CMD_IO, '/\burlwrite\b/'),
		  'web' =>                 array(R_CMD_EXEC, '/\bweb\b/'),
		  'instrcallback' =>       array(R_CMD_IO, '/\binstrcallback\b/'),
		  'instrfind' =>           array(R_CMD_IO, '/\binstrfind\b/'),
		  'instrfindall' =>        array(R_CMD_IO, '/\binstrfindall\b/'),
		  'isvalid' =>             array(R_CMD_IO, '/\bisvalid\b/'),
		  'readasync' =>           array(R_CMD_IO, '/\breadasync\b/'),
		  'record' =>              array(R_CMD_IO, '/\brecord\b/'),
		  'serial' =>              array(R_CMD_IO, '/\bserial\b/'),
		  'serialbreak' =>         array(R_CMD_IO, '/\bserialbreak\b/'),
		  'stopasync' =>           array(R_CMD_IO, '/\bstopasync\b/'),
		  'clear' =>               array(R_CMD_IO, '/\bclear\b/'),
		  // Category: GUI Building
		  'guide' =>               array(R_CMD_UI, '/\bguide\b/'),
		  'uicontrol' =>           array(R_CMD_UI, '/\buicontrol\b/'),
		  'uitable' =>             array(R_CMD_UI, '/\buitable\b/'),
		  'uipanel' =>             array(R_CMD_UI, '/\buipanel\b/'),
		  'uibuttongroup' =>       array(R_CMD_UI, '/\buibuttongroup\b/'),
		  'uimenu' =>              array(R_CMD_UI, '/\buimenu\b/'),
		  'uicontextmenu' =>       array(R_CMD_UI, '/\buicontextmenu\b/'),
		  'uitoolbar' =>           array(R_CMD_UI, '/\buitoolbar\b/'),
		  'uipushtool' =>          array(R_CMD_UI, '/\buipushtool\b/'),
		  'uitoggletool' =>        array(R_CMD_UI, '/\buitoggletool\b/'),
		  'dialog' =>              array(R_CMD_UI, '/\bdialog\b/'),
		  'errordlg' =>            array(R_CMD_UI, '/\berrordlg\b/'),
		  'helpdlg' =>             array(R_CMD_UI, '/\bhelpdlg\b/'),
		  'msgbox' =>              array(R_CMD_UI, '/\bmsgbox\b/'),
		  'questdlg' =>            array(R_CMD_UI, '/\bquestdlg\b/'),
		  'uigetpref' =>           array(R_CMD_UI, '/\buigetpref\b/'),
		  'uisetpref' =>           array(R_CMD_UI, '/\buisetpref\b/'),
		  'waitbar' =>             array(R_CMD_UI, '/\bwaitbar\b/'),
		  'warndlg' =>             array(R_CMD_UI, '/\bwarndlg\b/'),
		  'export2wsdlg' =>        array(R_CMD_UI, '/\bexport2wsdlg\b/'),
		  'inputdlg' =>            array(R_CMD_UI, '/\binputdlg\b/'),
		  'listdlg' =>             array(R_CMD_UI, '/\blistdlg\b/'),
		  'uisetcolor' =>          array(R_CMD_UI, '/\buisetcolor\b/'),
		  'uisetfont' =>           array(R_CMD_UI, '/\buisetfont\b/'),
		  'printpreview' =>        array(R_CMD_UI, '/\bprintpreview\b/'),
		  'uigetdir' =>            array(R_CMD_UI, '/\buigetdir\b/'),
		  'uigetfile' =>           array(R_CMD_UI, '/\buigetfile\b/'),
		  'uiopen' =>              array(R_CMD_UI, '/\buiopen\b/'),
		  'uiputfile' =>           array(R_CMD_UI, '/\buiputfile\b/'),
		  'uisave' =>              array(R_CMD_UI, '/\buisave\b/'),
		  'align' =>               array(R_CMD_UI, '/\balign\b/'),
		  'movegui' =>             array(R_CMD_UI, '/\bmovegui\b/'),
		  'getpixelposition' =>    array(R_CMD_UI, '/\bgetpixelposition\b/'),
		  'setpixelposition' =>    array(R_CMD_UI, '/\bsetpixelposition\b/'),
		  'listfonts' =>           array(R_CMD_UI, '/\blistfonts\b/'),
		  'textwrap' =>            array(R_CMD_UI, '/\btextwrap\b/'),
		  'uistack' =>             array(R_CMD_UI, '/\buistack\b/'),
		  'guidata' =>             array(R_CMD_UI, '/\bguidata\b/'),
		  'guihandles' =>          array(R_CMD_UI, '/\bguihandles\b/'),
		  'getappdata' =>          array(R_CMD_UI, '/\bgetappdata\b/'),
		  'isappdata' =>           array(R_CMD_UI, '/\bisappdata\b/'),
		  'rmappdata' =>           array(R_CMD_UI, '/\brmappdata\b/'),
		  'setappdata' =>          array(R_CMD_UI, '/\bsetappdata\b/'),
		  'uiresume' =>            array(R_CMD_UI, '/\buiresume\b/'),
		  'uiwait' =>              array(R_CMD_UI, '/\buiwait\b/'),
		  'waitfor' =>             array(R_CMD_UI, '/\bwaitfor(buttonpress)?\b/'),
		  'addpref' =>             array(R_CMD_UI, '/\baddpref\b/'),
		  'getpref' =>             array(R_CMD_UI, '/\bgetpref\b/'),
		  'ispref' =>              array(R_CMD_UI, '/\bispref\b/'),
		  'rmpref' =>              array(R_CMD_UI, '/\brmpref\b/'),
		  'setpref' =>             array(R_CMD_UI, '/\bsetpref\b/'),
		  //Category: Advanced Software Development
		  'notify' =>              array(R_CMD_UI, '/\bnotify\b/'),
		  'addlistener' =>         array(R_CMD_UI, '/\baddlistener\b/'),
		  'event.' =>              array(R_CMD_UI, '/\bevent\.(EventData|listener|PropertyEvent|proplistener)\b/'),
		  'saveobj' =>             array(R_CMD_IO, '/\bsaveobj\b/'),
		  'loadobj' =>             array(R_CMD_IO, '/\bloadobj\b/'),
		  // Category: Performance and Memoey
		  'profsave' =>            array(R_CMD_IO, '/\bprofsave\b/'),
		  'inmem' =>               array(R_CMD_INFO, '/\binmem\b/'),
		  // Category: Unit Testing Framework
		  'functiontests' =>       array(R_CMD_IO, '/\bfunctiontests\b/'),
		  'runtests' =>            array(R_CMD_IO, '/\bruntests\b/'),
		  // Category: Custom Documentation
		  'builddocsearchdb' =>    array(R_CMD_IO, '/\bbuilddocsearchdb\b/'),
		  // Category: External Programming Language Interfaces
		  'java' =>                array(R_CMD_IO|R_CMD_EXEC, '/\bjava(Array|classpath|addpath|rmpath|chk|Method|MethodEDT|Object|ObjectEDT)\b/'),
		  'isjava' =>              array(R_CMD_INFO, '/\bisjava\b/'),
		  'usejava' =>             array(R_CMD_INFO, '/\busejava\b/'),
		  'import' =>              array(R_CMD_IO, '/\bimport\b/'),
		  'inspect' =>             array(R_CMD_UI, '/\binspect\b/'),
		  'NET' =>                 array(R_CMD_IO|R_CMD_EXEC, '/\bNET(\.(addAssembly|isNETSupported|Assembly|NetException|createArray|disableAutoRelease|enableAutoRelease|setStaticProperty|convertArray|createGeneric|invokeGenericMethod|GenericClass))?\b/'),
		  'enableNETfromNetworkDrive' => array(R_CMD_IO|R_CMD_EXEC, '/\benableNETfromNetworkDrive\b/'),
		  'BeginInvoke' =>         array(R_CMD_IO|R_CMD_EXEC, '/\bBeginInvoke\b/'),
		  'EndInvoke' =>           array(R_CMD_IO|R_CMD_EXEC, '/\bEndInvoke\b/'),
		  'Combine' =>             array(R_CMD_IO|R_CMD_EXEC, '/\bCombine\b/'),
		  'Remove' =>              array(R_CMD_IO|R_CMD_EXEC, '/\bRemove\b/'),
		  'RemoveAll' =>           array(R_CMD_IO|R_CMD_EXEC, '/\bRemoveAll\b/'),
		  'bitand' =>              array(R_CMD_IO|R_CMD_EXEC, '/\bbitand\b/'),
		  'bitor' =>               array(R_CMD_IO|R_CMD_EXEC, '/\bbitor\b/'),
		  'bitxor' =>              array(R_CMD_IO|R_CMD_EXEC, '/\bbitxor\b/'),
		  'bitnot' =>              array(R_CMD_IO|R_CMD_EXEC, '/\bbitnot\b/'),
		  'actx'  =>               array(R_CMD_IO|R_CMD_EXEC, '\actx(server|control|controllist|controlselect|GetRunningServer)\b/'),
		  'iscom' =>               array(R_CMD_IO|R_CMD_EXEC, '/\biscom\b/'),
		  'isprop' =>              array(R_CMD_IO|R_CMD_EXEC, '/\bisprop\b/'),
		  'addproperty' =>         array(R_CMD_IO|R_CMD_EXEC, '/\baddproperty\b/'),
		  'invoke' =>              array(R_CMD_IO|R_CMD_EXEC, '/\binvoke\b/'),
		  'isevent' =>             array(R_CMD_IO|R_CMD_EXEC, '/\bisevent\b/'),
		  'events' =>              array(R_CMD_IO|R_CMD_EXEC, '/\bevents\b/'),
		  'eventlisteners' =>      array(R_CMD_IO|R_CMD_EXEC, '/\beventlisteners\b/'),
		  'registerevent' =>       array(R_CMD_IO|R_CMD_EXEC, '/\bregisterevent\b/'),
		  'unregisterallevents' => array(R_CMD_IO|R_CMD_EXEC, '/\bunregisterallevents\b/'),
		  'unregisterevent' =>     array(R_CMD_IO|R_CMD_EXEC, '/\bunregisterevent\b/'),
		  'isinterface' =>         array(R_CMD_IO|R_CMD_EXEC, '/\bisinterface\b/'),
		  'interfaces' =>          array(R_CMD_IO|R_CMD_EXEC, '/\binterfaces\b/'),
		  'release' =>             array(R_CMD_IO|R_CMD_EXEC, '/\brelease\b/'),
		  'move' =>                array(R_CMD_IO|R_CMD_EXEC, '/\bmove\b/'),
		  'Execute' =>             array(R_CMD_EXEC, '/\bExecute\b/'),
		  'Feval' =>               array(R_CMD_EXEC, '/\bFeval\b/'),
		  'GetCharArray' =>        array(R_CMD_IO, '/\bGetCharArray\b/'),
		  'PutCharArray' =>        array(R_CMD_IO, '/\bPutCharArray\b/'),
		  'GetFullMatrix' =>       array(R_CMD_IO, '/\bGetFullMatrix\b/'),
		  'PutFullMatrix' =>       array(R_CMD_IO, '/\bPutFullMatrix\b/'),
		  'GetVariable' =>         array(R_CMD_IO, '/\bGetVariable\b/'),
		  'GetWorkspaceData' =>    array(R_CMD_IO, '/\bGetWorkspaceData\b/'),
		  'PutWorkspaceData' =>    array(R_CMD_IO, '/\bPutWorkspaceData\b/'),
		  'CommandWindow' =>       array(R_CMD_UI, '/\b(Maximize|Minmize)CommandWindow\b/'),
		  'enableservice' =>       array(R_CMD_INFO, '/\benableservice\b/'),
		  'Quit' =>                array(R_CMD_EXEC, '/\bQuit\b/'),
		  'callSoapService' =>     array(R_CMD_IO, '/\bcallSoapService\b/'),
		  'createClassFromWsdl' => array(R_CMD_IO, '/\bcreateClassFromWsdl\b/'),
		  'createSoapMessage' =>   array(R_CMD_IO, '/\bcreateSoapMessage\b/'),
		  'parseSoapResponse' =>   array(R_CMD_IO, '/\bparseSoapResponse\b/'),
		  'loadlibrary' =>         array(R_CMD_EXEC, '/\bloadlibrary\b/'),
		  'unloadlibrary' =>       array(R_CMD_EXEC, '/\bunloadlibrary\b/'),
		  'libisloaded' =>         array(R_CMD_EXEC, '/\blibisloaded\b/'),
		  'calllib' =>             array(R_CMD_EXEC, '/\bcalllib\b/'),
		  'libfunctions' =>        array(R_CMD_EXEC, '/\blibfunctions\b/'),
		  'libfunctionsview' =>    array(R_CMD_UI, '/\blibfunctionsview\b/'),
		  'libstruct' =>           array(R_CMD_EXEC, '/\blibstruct\b/'),
		  'libpointer' =>          array(R_CMD_EXEC, '/\blibpointer\b/'),
		  'lib.pointer' =>         array(R_CMD_EXEC, '/\blib\.pointer\b/'),
		  //Category: Application Programming Interfaces to MATLAB
		  'mex' =>                 array(R_CMD_EXEC, '/\bmex(ext|\.getCompilerConfigurations)?\b/'),
		  'dbmex' =>               array(R_CMD_EXEC, '/\bdbmex\b/'),
		  // Category: Source Control Integration
		  'check' =>               array(R_CMD_EXEC, '/\bcheck(code|in|out)\b/'), 
		  'cmopts' =>              array(R_CMD_INFO, '/\bcmopts\b/'),
		  'customverctrl' =>       array(R_CMD_EXEC, '/\bcustomverctrl\b/'),
		  'undocheckout' =>        array(R_CMD_EXEC, '/\bundocheckout\b/'),
		  'verctrl' =>             array(R_CMD_IO|R_CMD_EXEC, '/\bverctrl\b/'),
		  // Category: Desktop Environment
		  'matlab' =>              array(R_CMD_EXEC, '/\bmatlab(rc|root|\.exception\.JavaException|\.apputil\.(create|package|install|run|getInstalledAppInfo|uninstall))?\b/'),
		  'startup' =>             array(R_CMD_EXEC, '/\bstartup\b/'),
		  'finish' =>              array(R_CMD_EXEC, '/\bfinish\b/'),
		  // Category: Basic Settings
		  'prefdir' =>             array(R_CMD_IO, '/\bprefdir\b/'),
		  'preferences' =>         array(R_CMD_UI, '/\bpreferences\b/'),
		  // Category: Platform and Licensing
		  'ismac' =>               array(R_CMD_INFO, '/\bismac\b/'),
		  'ispc' =>                array(R_CMD_INFO, '/\bispc\b/'),
		  'isstudent' =>           array(R_CMD_INFO, '/\bisstudent\b/'),
		  'isunix' =>              array(R_CMD_INFO, '/\bisunix\b/'),
		  'license' =>             array(R_CMD_INFO, '/\blicense\b/'),
		  'ver' =>                 array(R_CMD_INFO, '/\bver\b/'),
		  'verLessThan' =>         array(R_CMD_INFO, '/\bverLessThan\b/'),
		  'version' =>             array(R_CMD_INFO, '/\bversion\b/'),
		  // Category: Help and Support
		  'doc' =>                 array(R_CMD_UI, '/\bdoc\b/'),
		  'help' =>                array(R_CMD_UI, '/\bhelp\b/'),
		  'docsearch' =>           array(R_CMD_UI, '/\bdocsearch\b/'),
		  'lookfor' =>             array(R_CMD_UI, '/\blookfor\b/'),
		  'demo' =>                array(R_CMD_UI, '/\bdemo\b/'),
		  'echodemo' =>            array(R_CMD_UI, '/\bechodemo\b/')
		  );

?>
